server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citydb
    username: root
    password: nOtMYSQlP4ss999
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      enabled: true